In [1]:
import pandas as pd
import glob
import os
from geopy.geocoders import Nominatim
import requests
import json
import folium
from folium import FeatureGroup
from folium.plugins import MarkerCluster

In [2]:
df_new = pd.read_csv("Divvy_Bicycle_Stations_-_In_Service.csv")

In [3]:
df_new

,ID,Station Name,Total Docks,Docks in Service,Status,Latitude,Longitude,Location
0,1594046383808271024,Troy St & Jackson Blvd,9,9,In Service,41.877505,-87.704850,"(41.877505, -87.70485)"
1,641,Central Park Ave & Bloomingdale Ave,11,11,In Service,41.914166,-87.716755,"(41.914166, -87.716755)"
2,1683527931525155814,Public Rack - Cornell Ave & 87th Pl,1,1,In Service,41.736881,-87.583146,"(41.73688127, -87.58314552)"
3,367,Racine Ave & 35th St,15,15,In Service,41.830689,-87.656211,"(41.83068856472101, -87.65621066093445)"
4,1673852313397164648,Public Rack - Francisco Ave & Touhy Ave,2,2,In Service,42.011865,-87.701317,"(42.011865, -87.701317)"
...,...,...,...,...,...,...,...,...
1411,20,Sheffield Ave & Kingsbury St,15,15,In Service,41.910522,-87.653106,"(41.910522, -87.653106)"
1412,54,Ogden Ave & Chicago Ave,19,19,In Service,41.896362,-87.654061,"(41.896362458, -87.6540612729)"
1413,693,Baltimore Ave & 87th St,15,15,In Service,41.737336,-87.548515,"(41.737335600416664, -87.54851460456847)"
1414,718,Ewing Ave & Burnham Greenway,11,11,In Service,41.712749,-87.534814,"(41.71274876109496, -87.53481388092041)"
1415,762,Green St & Randolph St*,12,12,In Service,41.883602,-87.648627,"(41.883601657275165, -87.64862671494483)"

In [4]:
########       Creating Folium Visualization to visualize the stations in the area

In [5]:
def get_map_visualization(df):
    m = folium.Map(location=[42.060895,-88.212275], tiles='OpenStreetMap', zoom_start=5)
#     df = pd.read_csv(self.sheet+"_updated.csv")
        
    markerCluster = MarkerCluster().add_to(m)
    for i, row in df.iterrows():
        lat = df.at[i,'Latitude']
        lng = df.at[i,'Longitude']

        name = df.at[i,'Station Name']
        popup = str(df.at[i,'Station Name'])

        folium.Marker(location=[lat, lng],popup=name, icon=folium.Icon(color='red')).add_to(markerCluster)

    m.save("view.html")

In [6]:
get_map_visualization(df_new)