In [1]:
import pandas as pd
import numpy as np
import geopy.distance
from ast import literal_eval
import datetime as dt

In [2]:
# pip install geopy

In [3]:
stations = pd.read_csv("GetNearestBusAndTrainStation.csv")
stations = stations.drop(columns="Unnamed: 0")
stations

,ID,Station Name,Total Docks,Docks in Service,Status,Latitude,Longitude,Location,nearest_train_station_name,nearest_train_station_distance,nearest_bus_station_name,nearest_bus_station_distance
0,1.594050e+18,Troy St & Jackson Blvd,9,9,In Service,41.877505,-87.704850,"(41.877505, -87.70485)",Kedzie-Homan,0.365048,Jackson & Kedzie,0.081453
1,6.410000e+02,Central Park Ave & Bloomingdale Ave,11,11,In Service,41.914166,-87.716755,"(41.914166, -87.716755)",Logan Square,1.857948,Armitage & Central Park,0.342105
2,1.683530e+18,Public Rack - Cornell Ave & 87th Pl,1,1,In Service,41.736881,-87.583146,"(41.73688127, -87.58314552)",87th,3.462482,87th Street & East End,0.020426
3,3.670000e+02,Racine Ave & 35th St,15,15,In Service,41.830689,-87.656211,"(41.83068856472101, -87.65621066093445)",Ashland,1.213685,35th Street & Racine,0.050069
4,1.673850e+18,Public Rack - Francisco Ave & Touhy Ave,2,2,In Service,42.011865,-87.701317,"(42.011865, -87.701317)",Howard,2.486505,Touhy & Francisco,0.072283
...,...,...,...,...,...,...,...,...,...,...,...,...
1414,1.715850e+18,Public Rack - Lawndale Ave & Roosevelt,2,2,In Service,41.866225,-87.717918,"(41.866225, -87.717918)",Pulaski,1.058657,Roosevelt & Lawndale,0.005609
1415,1.715850e+18,Public Rack - Ashland Ave & 74th St,2,2,In Service,41.759735,-87.663736,"(41.759735, -87.663736)",Ashland/63rd,2.124192,74th Street & Ashland,0.034132
1416,3.200000e+02,Loomis St & Lexington St,19,19,In Service,41.872187,-87.661501,"(41.872187, -87.661501)",Racine,0.447972,Harrison & Loomis,0.217218
1417,5.400000e+01,Ogden Ave & Chicago Ave,19,19,In Service,41.896362,-87.654061,"(41.896362458, -87.6540612729)",Chicago,0.100847,Chicago & Milwaukee (Blue Line),0.086847
1418,6.930000e+02,Baltimore Ave & 87th St,15,15,In Service,41.737336,-87.548515,"(41.737335600416664, -87.54851460456847)",87th,6.343170,87th Street & Baltimore,0.033402

In [4]:
stations["efficiency"] = 0
stations

,ID,Station Name,Total Docks,Docks in Service,Status,Latitude,Longitude,Location,nearest_train_station_name,nearest_train_station_distance,nearest_bus_station_name,nearest_bus_station_distance,efficiency
0,1.594050e+18,Troy St & Jackson Blvd,9,9,In Service,41.877505,-87.704850,"(41.877505, -87.70485)",Kedzie-Homan,0.365048,Jackson & Kedzie,0.081453,0
1,6.410000e+02,Central Park Ave & Bloomingdale Ave,11,11,In Service,41.914166,-87.716755,"(41.914166, -87.716755)",Logan Square,1.857948,Armitage & Central Park,0.342105,0
2,1.683530e+18,Public Rack - Cornell Ave & 87th Pl,1,1,In Service,41.736881,-87.583146,"(41.73688127, -87.58314552)",87th,3.462482,87th Street & East End,0.020426,0
3,3.670000e+02,Racine Ave & 35th St,15,15,In Service,41.830689,-87.656211,"(41.83068856472101, -87.65621066093445)",Ashland,1.213685,35th Street & Racine,0.050069,0
4,1.673850e+18,Public Rack - Francisco Ave & Touhy Ave,2,2,In Service,42.011865,-87.701317,"(42.011865, -87.701317)",Howard,2.486505,Touhy & Francisco,0.072283,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,1.715850e+18,Public Rack - Lawndale Ave & Roosevelt,2,2,In Service,41.866225,-87.717918,"(41.866225, -87.717918)",Pulaski,1.058657,Roosevelt & Lawndale,0.005609,0
1415,1.715850e+18,Public Rack - Ashland Ave & 74th St,2,2,In Service,41.759735,-87.663736,"(41.759735, -87.663736)",Ashland/63rd,2.124192,74th Street & Ashland,0.034132,0
1416,3.200000e+02,Loomis St & Lexington St,19,19,In Service,41.872187,-87.661501,"(41.872187, -87.661501)",Racine,0.447972,Harrison & Loomis,0.217218,0
1417,5.400000e+01,Ogden Ave & Chicago Ave,19,19,In Service,41.896362,-87.654061,"(41.896362458, -87.6540612729)",Chicago,0.100847,Chicago & Milwaukee (Blue Line),0.086847,0
1418,6.930000e+02,Baltimore Ave & 87th St,15,15,In Service,41.737336,-87.548515,"(41.737335600416664, -87.54851460456847)",87th,6.343170,87th Street & Baltimore,0.033402,0

In [7]:
hist = pd.read_csv("Divvy_Bicycle_Stations_-_Historical_hourly.csv")
trips = pd.read_csv("divvy_trips_data_final.csv")

In [ ]:
trips["date"]=pd.to_datetime(trips["start_time"]).dt.date
demand=trips.value_counts(["start_station_name", "date"]).to_frame('counts')
demand.to_csv("./demand.csv")
demand.head()

In [ ]:
hist=hist.loc[hist["Status"]=="In Service"]
hist["date"]=pd.to_datetime(hist["Timestamp"]).dt.date
hist["Available Bikes"]=hist["Available Bikes"].astype(int)
supply = hist.groupby(["Station Name","date"])["Available Bikes"].sum().to_frame()
supply.to_csv("./supply.csv")
supply.head()

In [ ]:
s = pd.read_csv("supply.csv")
s=s.sort_values(by=["Station Name","date"])
d = pd.read_csv("demand.csv")
d=d.sort_values(by=["start_station_name", "date"])

In [ ]:
d["ratio"]=0

In [ ]:
for i in d.index:
    label = s.loc[(s["Station Name"]==d["start_station_name"][i]) & (s["date"]==d["date"][i])]["Available Bikes"]
    if len(label) !=0:
        d["ratio"][i]=float((label/d["counts"][i]).values)

In [ ]:
ratio=d.groupby(["start_station_name"]).mean()
ratio.to_csv("./ratio.csv")

In [ ]:
stations["Supply_to_Demand"]=0
stations["Demand"]=0
ratios = pd.read_csv("ratio.csv")
for i in stations.index:
    stations["nearest_train_station_distance"][i] = stations["nearest_train_station_distance"][i] * 0.621
    stations["nearest_bus_station_distance"][i] = stations["nearest_bus_station_distance"][i] * 0.621
    ind1=ratios.loc[ratios["start_station_name"]==stations["Station Name"][i]]["counts"]
    ind2=ratios.loc[ratios["start_station_name"]==stations["Station Name"][i]]["ratio"]
    if len(ind1)!=0 and len(ind2)!=0:
        stations["Demand"][i]=ind1.values
        stations["Supply_to_Demand"][i]=ind2.values
stations

In [ ]:
bus_weight = 0.5
train_weight = 0.3
dist_s1_weight = 0.8
dist_s2_weight = 0.5
dist_s3_weight = 0.3
stod_weight = 1.5

def find_efficiency(station_data):
    for i in range(len(station_data)):
        efficiency = station_data.loc[i]["nearest_bus_station_distance"] * bus_weight
        efficiency = efficiency + station_data.loc[i]["nearest_train_station_distance"] * train_weight
        

        dist = []
        for j in range(len(station_data)):
            if i != j:
                dist.append(geopy.distance.geodesic(literal_eval(station_data.loc[i]["Location"]), literal_eval(station_data.loc[j]["Location"])).miles)
        dist.sort()

        efficiency = efficiency + dist[0]*dist_s1_weight
        efficiency = efficiency + dist[1]*dist_s2_weight
        efficiency = efficiency + dist[2]*dist_s3_weight
        
        efficiency = efficiency + station_data.loc[i]["Supply_to_Demand"] * stod_weight

        station_data.loc[i,"efficiency"] = efficiency

In [ ]:
find_efficiency(stations)
stations

In [ ]:
df_min_max_scaled = stations.copy()
column = 'efficiency'
df_min_max_scaled[column] = (df_min_max_scaled[column] - df_min_max_scaled[column].min()) / (df_min_max_scaled[column].max() - df_min_max_scaled[column].min())

In [ ]:
df_min_max_scaled

In [ ]:
stations.to_csv('stations_efficiency.csv')

In [13]:
eff = pd.read_csv("stations_efficiency_new.csv")

In [14]:
eff

,Unnamed: 0,ID,Station Name,Total Docks,Docks in Service,Status,Latitude,Longitude,Location,nearest_train_station_name,nearest_train_station_distance,nearest_bus_station_name,nearest_bus_station_distance,efficiency,Supply_to_Demand,Demand
0,0,1.594050e+18,Troy St & Jackson Blvd,9,9,In Service,41.877505,-87.704850,"(41.877505, -87.70485)",Kedzie-Homan,0.140777,Jackson & Kedzie,0.031412,52.438123,34.557692,1.346154
1,1,6.410000e+02,Central Park Ave & Bloomingdale Ave,11,11,In Service,41.914166,-87.716755,"(41.914166, -87.716755)",Logan Square,0.716501,Armitage & Central Park,0.131930,56.120585,36.836575,7.582558
2,2,1.683530e+18,Public Rack - Cornell Ave & 87th Pl,1,1,In Service,41.736881,-87.583146,"(41.73688127, -87.58314552)",87th,1.335275,87th Street & East End,0.007877,12.633609,8.100000,1.200000
3,3,3.670000e+02,Racine Ave & 35th St,15,15,In Service,41.830689,-87.656211,"(41.83068856472101, -87.65621066093445)",Ashland,0.468047,35th Street & Racine,0.019309,108.372510,71.602211,3.347193
4,4,1.673850e+18,Public Rack - Francisco Ave & Touhy Ave,2,2,In Service,42.011865,-87.701317,"(42.011865, -87.701317)",Howard,0.958898,Touhy & Francisco,0.027875,14.637109,9.500000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,1414,1.715850e+18,Public Rack - Lawndale Ave & Roosevelt,2,2,In Service,41.866225,-87.717918,"(41.866225, -87.717918)",Pulaski,0.408262,Roosevelt & Lawndale,0.002163,0.325508,0.000000,0.000000
1415,1415,1.715850e+18,Public Rack - Ashland Ave & 74th St,2,2,In Service,41.759735,-87.663736,"(41.759735, -87.663736)",Ashland/63rd,0.819176,74th Street & Ashland,0.013163,0.397976,0.000000,0.000000
1416,1416,3.200000e+02,Loomis St & Lexington St,19,19,In Service,41.872187,-87.661501,"(41.872187, -87.661501)",Racine,0.172757,Harrison & Loomis,0.083768,19.684723,12.757780,37.920830
1417,1417,5.400000e+01,Ogden Ave & Chicago Ave,19,19,In Service,41.896362,-87.654061,"(41.896362458, -87.6540612729)",Chicago,0.038891,Chicago & Milwaukee (Blue Line),0.033492,32.457729,21.361908,26.010023
1418,1418,6.930000e+02,Baltimore Ave & 87th St,15,15,In Service,41.737336,-87.548515,"(41.737335600416664, -87.54851460456847)",87th,2.446187,87th Street & Baltimore,0.012881,74.420236,48.765399,3.148026

In [15]:
df_min_max_scaled = eff.copy()
column = 'efficiency'
df_min_max_scaled[column] = (df_min_max_scaled[column] - df_min_max_scaled[column].min()) / (df_min_max_scaled[column].max() - df_min_max_scaled[column].min())

In [19]:
df_min_max_scaled = eff.copy()
column = 'Supply_to_Demand'
df_min_max_scaled[column] = (df_min_max_scaled[column] - df_min_max_scaled[column].min()) / (df_min_max_scaled[column].max() - df_min_max_scaled[column].min())

In [16]:
print(df_min_max_scaled["efficiency"].mean())

0.18125466824910402

In [17]:
print(df_min_max_scaled["efficiency"].median())

0.11577427823930153

In [20]:
print(df_min_max_scaled["Supply_to_Demand"].mean())
print(df_min_max_scaled["Supply_to_Demand"].median())

0.17883376758242117
0.11433373726049724

In [21]:
bus_weight = 0.5
train_weight = 0.3
dist_s1_weight = 0.8
dist_s2_weight = 0.5
dist_s3_weight = 0.3
stod_weight = 1.5

def find_efficiency(station_data):
    for i in range(len(station_data)):
        efficiency = station_data.loc[i]["nearest_bus_station_distance"] * bus_weight
        efficiency = efficiency + station_data.loc[i]["nearest_train_station_distance"] * train_weight
        

        dist = []
        for j in range(len(station_data)):
            if i != j:
                dist.append(geopy.distance.geodesic(literal_eval(station_data.loc[i]["Location"]), literal_eval(station_data.loc[j]["Location"])).miles)
        dist.sort()

        efficiency = efficiency + dist[0]*dist_s1_weight
        efficiency = efficiency + dist[1]*dist_s2_weight
        efficiency = efficiency + dist[2]*dist_s3_weight
        if 0.3<station_data.loc[i]["Supply_to_Demand"]<0.5:
            efficiency = efficiency + station_data.loc[i]["Supply_to_Demand"] * stod_weight
        else:
            efficiency = efficiency - station_data.loc[i]["Supply_to_Demand"] * stod_weight


        station_data.loc[i,"efficiency"] = efficiency

In [22]:
find_efficiency(eff)
eff

,Unnamed: 0,ID,Station Name,Total Docks,Docks in Service,Status,Latitude,Longitude,Location,nearest_train_station_name,nearest_train_station_distance,nearest_bus_station_name,nearest_bus_station_distance,efficiency,Supply_to_Demand,Demand
0,0,1.594050e+18,Troy St & Jackson Blvd,9,9,In Service,41.877505,-87.704850,"(41.877505, -87.70485)",Kedzie-Homan,0.140777,Jackson & Kedzie,0.031412,-51.234954,34.557692,1.346154
1,1,6.410000e+02,Central Park Ave & Bloomingdale Ave,11,11,In Service,41.914166,-87.716755,"(41.914166, -87.716755)",Logan Square,0.716501,Armitage & Central Park,0.131930,-54.389139,36.836575,7.582558
2,2,1.683530e+18,Public Rack - Cornell Ave & 87th Pl,1,1,In Service,41.736881,-87.583146,"(41.73688127, -87.58314552)",87th,1.335275,87th Street & East End,0.007877,-11.666391,8.100000,1.200000
3,3,3.670000e+02,Racine Ave & 35th St,15,15,In Service,41.830689,-87.656211,"(41.83068856472101, -87.65621066093445)",Ashland,0.468047,35th Street & Racine,0.019309,-106.434125,71.602211,3.347193
4,4,1.673850e+18,Public Rack - Francisco Ave & Touhy Ave,2,2,In Service,42.011865,-87.701317,"(42.011865, -87.701317)",Howard,0.958898,Touhy & Francisco,0.027875,-13.862891,9.500000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,1414,1.715850e+18,Public Rack - Lawndale Ave & Roosevelt,2,2,In Service,41.866225,-87.717918,"(41.866225, -87.717918)",Pulaski,0.408262,Roosevelt & Lawndale,0.002163,0.325508,0.000000,0.000000
1415,1415,1.715850e+18,Public Rack - Ashland Ave & 74th St,2,2,In Service,41.759735,-87.663736,"(41.759735, -87.663736)",Ashland/63rd,0.819176,74th Street & Ashland,0.013163,0.397976,0.000000,0.000000
1416,1416,3.200000e+02,Loomis St & Lexington St,19,19,In Service,41.872187,-87.661501,"(41.872187, -87.661501)",Racine,0.172757,Harrison & Loomis,0.083768,-18.588616,12.757780,37.920830
1417,1417,5.400000e+01,Ogden Ave & Chicago Ave,19,19,In Service,41.896362,-87.654061,"(41.896362458, -87.6540612729)",Chicago,0.038891,Chicago & Milwaukee (Blue Line),0.033492,-31.627996,21.361908,26.010023
1418,1418,6.930000e+02,Baltimore Ave & 87th St,15,15,In Service,41.737336,-87.548515,"(41.737335600416664, -87.54851460456847)",87th,2.446187,87th Street & Baltimore,0.012881,-71.875959,48.765399,3.148026

In [23]:
df_min_max_scaled = eff.copy()
column = 'efficiency'
df_min_max_scaled[column] = (df_min_max_scaled[column] - df_min_max_scaled[column].min()) / (df_min_max_scaled[column].max() - df_min_max_scaled[column].min())

In [25]:
df_min_max_scaled

,Unnamed: 0,ID,Station Name,Total Docks,Docks in Service,Status,Latitude,Longitude,Location,nearest_train_station_name,nearest_train_station_distance,nearest_bus_station_name,nearest_bus_station_distance,efficiency,Supply_to_Demand,Demand
0,0,1.594050e+18,Troy St & Jackson Blvd,9,9,In Service,41.877505,-87.704850,"(41.877505, -87.70485)",Kedzie-Homan,0.140777,Jackson & Kedzie,0.031412,0.736743,34.557692,1.346154
1,1,6.410000e+02,Central Park Ave & Bloomingdale Ave,11,11,In Service,41.914166,-87.716755,"(41.914166, -87.716755)",Logan Square,0.716501,Armitage & Central Park,0.131930,0.721076,36.836575,7.582558
2,2,1.683530e+18,Public Rack - Cornell Ave & 87th Pl,1,1,In Service,41.736881,-87.583146,"(41.73688127, -87.58314552)",87th,1.335275,87th Street & East End,0.007877,0.933276,8.100000,1.200000
3,3,3.670000e+02,Racine Ave & 35th St,15,15,In Service,41.830689,-87.656211,"(41.83068856472101, -87.65621066093445)",Ashland,0.468047,35th Street & Racine,0.019309,0.462573,71.602211,3.347193
4,4,1.673850e+18,Public Rack - Francisco Ave & Touhy Ave,2,2,In Service,42.011865,-87.701317,"(42.011865, -87.701317)",Howard,0.958898,Touhy & Francisco,0.027875,0.922366,9.500000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,1414,1.715850e+18,Public Rack - Lawndale Ave & Roosevelt,2,2,In Service,41.866225,-87.717918,"(41.866225, -87.717918)",Pulaski,0.408262,Roosevelt & Lawndale,0.002163,0.992839,0.000000,0.000000
1415,1415,1.715850e+18,Public Rack - Ashland Ave & 74th St,2,2,In Service,41.759735,-87.663736,"(41.759735, -87.663736)",Ashland/63rd,0.819176,74th Street & Ashland,0.013163,0.993199,0.000000,0.000000
1416,1416,3.200000e+02,Loomis St & Lexington St,19,19,In Service,41.872187,-87.661501,"(41.872187, -87.661501)",Racine,0.172757,Harrison & Loomis,0.083768,0.898894,12.757780,37.920830
1417,1417,5.400000e+01,Ogden Ave & Chicago Ave,19,19,In Service,41.896362,-87.654061,"(41.896362458, -87.6540612729)",Chicago,0.038891,Chicago & Milwaukee (Blue Line),0.033492,0.834129,21.361908,26.010023
1418,1418,6.930000e+02,Baltimore Ave & 87th St,15,15,In Service,41.737336,-87.548515,"(41.737335600416664, -87.54851460456847)",87th,2.446187,87th Street & Baltimore,0.012881,0.634221,48.765399,3.148026

In [28]:
df_min_max_scaled.to_csv("final_efficiency.csv")

In [2]:
df_min_max_scaled = pd.read_csv("final_efficiency.csv")

In [11]:
station_community_mapping = pd.read_csv("StationCommunityMapping.csv")
station_community_mapping.head()

,Unnamed: 0,ID,Station Name,Total Docks,Docks in Service,Status,Latitude,Longitude,Location,community_area
0,0,1594046383808271024,Troy St & Jackson Blvd,9,9,In Service,41.877505,-87.704850,"(41.877505, -87.70485)",EAST_GARFIELD_PARK
1,1,641,Central Park Ave & Bloomingdale Ave,11,11,In Service,41.914166,-87.716755,"(41.914166, -87.716755)",LOGAN_SQUARE
2,2,1683527931525155814,Public Rack - Cornell Ave & 87th Pl,1,1,In Service,41.736881,-87.583146,"(41.73688127, -87.58314552)",CALUMET_HEIGHTS
3,3,367,Racine Ave & 35th St,15,15,In Service,41.830689,-87.656211,"(41.83068856472101, -87.65621066093445)",BRIDGEPORT
4,4,1673852313397164648,Public Rack - Francisco Ave & Touhy Ave,2,2,In Service,42.011865,-87.701317,"(42.011865, -87.701317)",WEST_RIDGE

In [12]:
after_clustering = pd.read_csv("after_clustering.csv")
after_clustering.head()

,Unnamed: 0,ID,Station Name,Total Docks,Docks in Service,Status,Latitude,Longitude,Location,cluster
0,0,1594046383808271024,Troy St & Jackson Blvd,9,9,In Service,41.877505,-87.704850,"(41.877505, -87.70485)",19
1,1,641,Central Park Ave & Bloomingdale Ave,11,11,In Service,41.914166,-87.716755,"(41.914166, -87.716755)",11
2,2,1683527931525155814,Public Rack - Cornell Ave & 87th Pl,1,1,In Service,41.736881,-87.583146,"(41.73688127, -87.58314552)",22
3,3,367,Racine Ave & 35th St,15,15,In Service,41.830689,-87.656211,"(41.83068856472101, -87.65621066093445)",5
4,4,1673852313397164648,Public Rack - Francisco Ave & Touhy Ave,2,2,In Service,42.011865,-87.701317,"(42.011865, -87.701317)",13

In [13]:
df_min_max_scaled['cluster'] = after_clustering['cluster']
df_min_max_scaled['community_area'] = station_community_mapping['community_area']

In [7]:
newDf1 = pd.DataFrame(df_min_max_scaled.groupby("cluster")["efficiency"].mean()).reset_index(drop=False)

In [10]:
newDf1.sort_values(["efficiency"],ascending=True)

    cluster  efficiency
13     13.0    0.721297
9       9.0    0.723811
1       1.0    0.737939
5       5.0    0.741361
4       4.0    0.751614
14     14.0    0.754729
11     11.0    0.772049
15     15.0    0.779252
7       7.0    0.784805
0       0.0    0.785749
18     18.0    0.790275
12     12.0    0.790880
22     22.0    0.816109
8       8.0    0.849507
19     19.0    0.849715
17     17.0    0.850421
23     23.0    0.854419
2       2.0    0.863922
10     10.0    0.867696
24     24.0    0.868832
3       3.0    0.871843
6       6.0    0.891608
21     21.0    0.892880
20     20.0    0.921031
16     16.0    0.930941

In [14]:
newDf2 = pd.DataFrame(df_min_max_scaled.groupby("community_area")["efficiency"].mean()).reset_index(drop=False)

In [19]:
newDf2 = newDf2.sort_values(["efficiency"],ascending=True)
newDf2 = newDf2[newDf2.community_area != "Not Found"]

In [20]:
newDf2

   community_area  efficiency
39  MCKINLEY_PARK    0.561497
55    ROGERS_PARK    0.595336
10     BRIDGEPORT    0.603694
22    FULLER_PARK    0.611356
2   ARMOUR_SQUARE    0.648272
..            ...         ...
15   CHICAGO_LAWN    0.937906
67      WEST_LAWN    0.939729
64    WEST_ELSDON    0.950107
51        OAKLAND    0.994226
3         ASHBURN    0.996190

[71 rows x 2 columns]