In [23]:
import pandas as pd
import numpy as np
import geopy.distance
from ast import literal_eval
import datetime as dt

In [ ]:
# pip install geopy

In [24]:
stations = pd.read_csv("GetNearestBusAndTrainStation.csv")
stations = stations.drop(columns="Unnamed: 0")
stations

,ID,Station Name,Total Docks,Docks in Service,Status,Latitude,Longitude,Location,nearest_train_station_name,nearest_train_station_distance,nearest_bus_station_name,nearest_bus_station_distance
0,1.594050e+18,Troy St & Jackson Blvd,9,9,In Service,41.877505,-87.704850,"(41.877505, -87.70485)",Kedzie-Homan,0.365048,Jackson & Kedzie,0.081453
1,6.410000e+02,Central Park Ave & Bloomingdale Ave,11,11,In Service,41.914166,-87.716755,"(41.914166, -87.716755)",Logan Square,1.857948,Armitage & Central Park,0.342105
2,1.683530e+18,Public Rack - Cornell Ave & 87th Pl,1,1,In Service,41.736881,-87.583146,"(41.73688127, -87.58314552)",87th,3.462482,87th Street & East End,0.020426
3,3.670000e+02,Racine Ave & 35th St,15,15,In Service,41.830689,-87.656211,"(41.83068856472101, -87.65621066093445)",Ashland,1.213685,35th Street & Racine,0.050069
4,1.673850e+18,Public Rack - Francisco Ave & Touhy Ave,2,2,In Service,42.011865,-87.701317,"(42.011865, -87.701317)",Howard,2.486505,Touhy & Francisco,0.072283
...,...,...,...,...,...,...,...,...,...,...,...,...
1414,1.715850e+18,Public Rack - Lawndale Ave & Roosevelt,2,2,In Service,41.866225,-87.717918,"(41.866225, -87.717918)",Pulaski,1.058657,Roosevelt & Lawndale,0.005609
1415,1.715850e+18,Public Rack - Ashland Ave & 74th St,2,2,In Service,41.759735,-87.663736,"(41.759735, -87.663736)",Ashland/63rd,2.124192,74th Street & Ashland,0.034132
1416,3.200000e+02,Loomis St & Lexington St,19,19,In Service,41.872187,-87.661501,"(41.872187, -87.661501)",Racine,0.447972,Harrison & Loomis,0.217218
1417,5.400000e+01,Ogden Ave & Chicago Ave,19,19,In Service,41.896362,-87.654061,"(41.896362458, -87.6540612729)",Chicago,0.100847,Chicago & Milwaukee (Blue Line),0.086847
1418,6.930000e+02,Baltimore Ave & 87th St,15,15,In Service,41.737336,-87.548515,"(41.737335600416664, -87.54851460456847)",87th,6.343170,87th Street & Baltimore,0.033402

In [25]:
stations["efficiency"] = 0
stations

,ID,Station Name,Total Docks,Docks in Service,Status,Latitude,Longitude,Location,nearest_train_station_name,nearest_train_station_distance,nearest_bus_station_name,nearest_bus_station_distance,efficiency
0,1.594050e+18,Troy St & Jackson Blvd,9,9,In Service,41.877505,-87.704850,"(41.877505, -87.70485)",Kedzie-Homan,0.365048,Jackson & Kedzie,0.081453,0
1,6.410000e+02,Central Park Ave & Bloomingdale Ave,11,11,In Service,41.914166,-87.716755,"(41.914166, -87.716755)",Logan Square,1.857948,Armitage & Central Park,0.342105,0
2,1.683530e+18,Public Rack - Cornell Ave & 87th Pl,1,1,In Service,41.736881,-87.583146,"(41.73688127, -87.58314552)",87th,3.462482,87th Street & East End,0.020426,0
3,3.670000e+02,Racine Ave & 35th St,15,15,In Service,41.830689,-87.656211,"(41.83068856472101, -87.65621066093445)",Ashland,1.213685,35th Street & Racine,0.050069,0
4,1.673850e+18,Public Rack - Francisco Ave & Touhy Ave,2,2,In Service,42.011865,-87.701317,"(42.011865, -87.701317)",Howard,2.486505,Touhy & Francisco,0.072283,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,1.715850e+18,Public Rack - Lawndale Ave & Roosevelt,2,2,In Service,41.866225,-87.717918,"(41.866225, -87.717918)",Pulaski,1.058657,Roosevelt & Lawndale,0.005609,0
1415,1.715850e+18,Public Rack - Ashland Ave & 74th St,2,2,In Service,41.759735,-87.663736,"(41.759735, -87.663736)",Ashland/63rd,2.124192,74th Street & Ashland,0.034132,0
1416,3.200000e+02,Loomis St & Lexington St,19,19,In Service,41.872187,-87.661501,"(41.872187, -87.661501)",Racine,0.447972,Harrison & Loomis,0.217218,0
1417,5.400000e+01,Ogden Ave & Chicago Ave,19,19,In Service,41.896362,-87.654061,"(41.896362458, -87.6540612729)",Chicago,0.100847,Chicago & Milwaukee (Blue Line),0.086847,0
1418,6.930000e+02,Baltimore Ave & 87th St,15,15,In Service,41.737336,-87.548515,"(41.737335600416664, -87.54851460456847)",87th,6.343170,87th Street & Baltimore,0.033402,0

In [33]:
hist = pd.read_csv("Divvy_Bicycle_Stations_-_Historical_hourly.csv")
trips = pd.read_csv("divvy_trips_data_final.csv")

/var/folders/d5/kbrmypln0nnfft9htnrprljc0000gp/T/ipykernel_8588/217515.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  hist = pd.read_csv("Divvy_Bicycle_Stations_-_Historical_hourly.csv")
/var/folders/d5/kbrmypln0nnfft9htnrprljc0000gp/T/ipykernel_8588/217515.py:2: DtypeWarning: Columns (3,5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  trips = pd.read_csv("divvy_trips_data_final.csv")

In [34]:
trips["date"]=pd.to_datetime(trips["start_time"]).dt.date
demand=trips.value_counts(["start_station_name", "date"]).to_frame('counts')
demand.to_csv("./demand.csv")
demand.head()

                                    counts
start_station_name      date
Streeter Dr & Grand Ave 2022-04-23    1082
                        2022-05-29    1056
                        2018-08-11    1051
                        2022-07-03    1040
                        2018-09-02    1021

In [35]:
hist=hist.loc[hist["Status"]=="In Service"]
hist["date"]=pd.to_datetime(hist["Timestamp"]).dt.date
hist["Available Bikes"]=hist["Available Bikes"].astype(int)
supply = hist.groupby(["Station Name","date"])["Available Bikes"].sum().to_frame()
supply.to_csv("./supply.csv")
supply.head()

                                     Available Bikes
Station Name             date
10101 S Stony Island Ave 2022-05-17                0
                         2022-05-18                0
                         2022-07-07                0
                         2022-07-08                0
                         2022-07-09                0

In [ ]:
s = pd.read_csv("supply.csv")
s=s.sort_values(by=["Station Name","date"])
d = pd.read_csv("demand.csv")
d=d.sort_values(by=["start_station_name", "date"])

In [ ]:
d["ratio"]=0

In [ ]:
for i in d.index:
    label = s.loc[(s["Station Name"]==d["start_station_name"][i]) & (s["date"]==d["date"][i])]["Available Bikes"]
    if len(label) !=0:
        d["ratio"][i]=float((label/d["counts"][i]).values)

In [ ]:
ratio=d.groupby(["start_station_name"]).mean()
ratio.to_csv("./ratio.csv")

In [27]:
stations["Supply_to_Demand"]=0
stations["Demand"]=0
ratios = pd.read_csv("ratio.csv")
for i in stations.index:
    stations["nearest_train_station_distance"][i] = stations["nearest_train_station_distance"][i] * 0.621
    stations["nearest_bus_station_distance"][i] = stations["nearest_bus_station_distance"][i] * 0.621
    ind1=ratios.loc[ratios["start_station_name"]==stations["Station Name"][i]]["counts"]
    ind2=ratios.loc[ratios["start_station_name"]==stations["Station Name"][i]]["ratio"]
    if len(ind1)!=0 and len(ind2)!=0:
        stations["Demand"][i]=ind1.values
        stations["Supply_to_Demand"][i]=ind2.values
stations

/var/folders/d5/kbrmypln0nnfft9htnrprljc0000gp/T/ipykernel_8588/1325862165.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stations["nearest_train_station_distance"][i] = stations["nearest_train_station_distance"][i] * 0.621
/var/folders/d5/kbrmypln0nnfft9htnrprljc0000gp/T/ipykernel_8588/1325862165.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stations["nearest_bus_station_distance"][i] = stations["nearest_bus_station_distance"][i] * 0.621
/var/folders/d5/kbrmypln0nnfft9htnrprljc0000gp/T/ipykernel_8588/1325862165.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stations["Demand"][i]=ind1.values
/var/folders/d5/kbrmypln0nnfft9htnrprljc0000gp/T/ipykernel_8588/1325862165.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stations["Supply_to_Demand"][i]=ind2.values

,ID,Station Name,Total Docks,Docks in Service,Status,Latitude,Longitude,Location,nearest_train_station_name,nearest_train_station_distance,nearest_bus_station_name,nearest_bus_station_distance,efficiency,Supply_to_Demand,Demand
0,1.594050e+18,Troy St & Jackson Blvd,9,9,In Service,41.877505,-87.704850,"(41.877505, -87.70485)",Kedzie-Homan,0.140777,Jackson & Kedzie,0.031412,0,34.557692,1.346154
1,6.410000e+02,Central Park Ave & Bloomingdale Ave,11,11,In Service,41.914166,-87.716755,"(41.914166, -87.716755)",Logan Square,0.716501,Armitage & Central Park,0.131930,0,36.836575,7.582558
2,1.683530e+18,Public Rack - Cornell Ave & 87th Pl,1,1,In Service,41.736881,-87.583146,"(41.73688127, -87.58314552)",87th,1.335275,87th Street & East End,0.007877,0,8.100000,1.200000
3,3.670000e+02,Racine Ave & 35th St,15,15,In Service,41.830689,-87.656211,"(41.83068856472101, -87.65621066093445)",Ashland,0.468047,35th Street & Racine,0.019309,0,71.602211,3.347193
4,1.673850e+18,Public Rack - Francisco Ave & Touhy Ave,2,2,In Service,42.011865,-87.701317,"(42.011865, -87.701317)",Howard,0.958898,Touhy & Francisco,0.027875,0,9.500000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,1.715850e+18,Public Rack - Lawndale Ave & Roosevelt,2,2,In Service,41.866225,-87.717918,"(41.866225, -87.717918)",Pulaski,0.408262,Roosevelt & Lawndale,0.002163,0,0.000000,0.000000
1415,1.715850e+18,Public Rack - Ashland Ave & 74th St,2,2,In Service,41.759735,-87.663736,"(41.759735, -87.663736)",Ashland/63rd,0.819176,74th Street & Ashland,0.013163,0,0.000000,0.000000
1416,3.200000e+02,Loomis St & Lexington St,19,19,In Service,41.872187,-87.661501,"(41.872187, -87.661501)",Racine,0.172757,Harrison & Loomis,0.083768,0,12.757780,37.920830
1417,5.400000e+01,Ogden Ave & Chicago Ave,19,19,In Service,41.896362,-87.654061,"(41.896362458, -87.6540612729)",Chicago,0.038891,Chicago & Milwaukee (Blue Line),0.033492,0,21.361908,26.010023
1418,6.930000e+02,Baltimore Ave & 87th St,15,15,In Service,41.737336,-87.548515,"(41.737335600416664, -87.54851460456847)",87th,2.446187,87th Street & Baltimore,0.012881,0,48.765399,3.148026

In [28]:
bus_weight = 0.5
train_weight = 0.3
dist_s1_weight = 0.8
dist_s2_weight = 0.5
dist_s3_weight = 0.3
stod_weight = 1.5

def find_efficiency(station_data):
    for i in range(len(station_data)):
        efficiency = station_data.loc[i]["nearest_bus_station_distance"] * bus_weight
        efficiency = efficiency + station_data.loc[i]["nearest_train_station_distance"] * train_weight
        

        dist = []
        for j in range(len(station_data)):
            if i != j:
                dist.append(geopy.distance.geodesic(literal_eval(station_data.loc[i]["Location"]), literal_eval(station_data.loc[j]["Location"])).miles)
        dist.sort()

        efficiency = efficiency + dist[0]*dist_s1_weight
        efficiency = efficiency + dist[1]*dist_s2_weight
        efficiency = efficiency + dist[2]*dist_s3_weight
        
        efficiency = efficiency + station_data.loc[i]["Supply_to_Demand"] * stod_weight

        station_data.loc[i,"efficiency"] = efficiency

In [29]:
find_efficiency(stations)
stations

,ID,Station Name,Total Docks,Docks in Service,Status,Latitude,Longitude,Location,nearest_train_station_name,nearest_train_station_distance,nearest_bus_station_name,nearest_bus_station_distance,efficiency,Supply_to_Demand,Demand
0,1.594050e+18,Troy St & Jackson Blvd,9,9,In Service,41.877505,-87.704850,"(41.877505, -87.70485)",Kedzie-Homan,0.140777,Jackson & Kedzie,0.031412,52.438123,34.557692,1.346154
1,6.410000e+02,Central Park Ave & Bloomingdale Ave,11,11,In Service,41.914166,-87.716755,"(41.914166, -87.716755)",Logan Square,0.716501,Armitage & Central Park,0.131930,56.120585,36.836575,7.582558
2,1.683530e+18,Public Rack - Cornell Ave & 87th Pl,1,1,In Service,41.736881,-87.583146,"(41.73688127, -87.58314552)",87th,1.335275,87th Street & East End,0.007877,12.633609,8.100000,1.200000
3,3.670000e+02,Racine Ave & 35th St,15,15,In Service,41.830689,-87.656211,"(41.83068856472101, -87.65621066093445)",Ashland,0.468047,35th Street & Racine,0.019309,108.372510,71.602211,3.347193
4,1.673850e+18,Public Rack - Francisco Ave & Touhy Ave,2,2,In Service,42.011865,-87.701317,"(42.011865, -87.701317)",Howard,0.958898,Touhy & Francisco,0.027875,14.637109,9.500000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,1.715850e+18,Public Rack - Lawndale Ave & Roosevelt,2,2,In Service,41.866225,-87.717918,"(41.866225, -87.717918)",Pulaski,0.408262,Roosevelt & Lawndale,0.002163,0.325508,0.000000,0.000000
1415,1.715850e+18,Public Rack - Ashland Ave & 74th St,2,2,In Service,41.759735,-87.663736,"(41.759735, -87.663736)",Ashland/63rd,0.819176,74th Street & Ashland,0.013163,0.397976,0.000000,0.000000
1416,3.200000e+02,Loomis St & Lexington St,19,19,In Service,41.872187,-87.661501,"(41.872187, -87.661501)",Racine,0.172757,Harrison & Loomis,0.083768,19.684723,12.757780,37.920830
1417,5.400000e+01,Ogden Ave & Chicago Ave,19,19,In Service,41.896362,-87.654061,"(41.896362458, -87.6540612729)",Chicago,0.038891,Chicago & Milwaukee (Blue Line),0.033492,32.457729,21.361908,26.010023
1418,6.930000e+02,Baltimore Ave & 87th St,15,15,In Service,41.737336,-87.548515,"(41.737335600416664, -87.54851460456847)",87th,2.446187,87th Street & Baltimore,0.012881,74.420236,48.765399,3.148026

In [30]:
df_min_max_scaled = stations.copy()
column = 'efficiency'
df_min_max_scaled[column] = (df_min_max_scaled[column] - df_min_max_scaled[column].min()) / (df_min_max_scaled[column].max() - df_min_max_scaled[column].min())

In [31]:
df_min_max_scaled

,ID,Station Name,Total Docks,Docks in Service,Status,Latitude,Longitude,Location,nearest_train_station_name,nearest_train_station_distance,nearest_bus_station_name,nearest_bus_station_distance,efficiency,Supply_to_Demand,Demand
0,1.594050e+18,Troy St & Jackson Blvd,9,9,In Service,41.877505,-87.704850,"(41.877505, -87.70485)",Kedzie-Homan,0.140777,Jackson & Kedzie,0.031412,0.261219,34.557692,1.346154
1,6.410000e+02,Central Park Ave & Bloomingdale Ave,11,11,In Service,41.914166,-87.716755,"(41.914166, -87.716755)",Logan Square,0.716501,Armitage & Central Park,0.131930,0.279586,36.836575,7.582558
2,1.683530e+18,Public Rack - Cornell Ave & 87th Pl,1,1,In Service,41.736881,-87.583146,"(41.73688127, -87.58314552)",87th,1.335275,87th Street & East End,0.007877,0.062685,8.100000,1.200000
3,3.670000e+02,Racine Ave & 35th St,15,15,In Service,41.830689,-87.656211,"(41.83068856472101, -87.65621066093445)",Ashland,0.468047,35th Street & Racine,0.019309,0.540205,71.602211,3.347193
4,1.673850e+18,Public Rack - Francisco Ave & Touhy Ave,2,2,In Service,42.011865,-87.701317,"(42.011865, -87.701317)",Howard,0.958898,Touhy & Francisco,0.027875,0.072678,9.500000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,1.715850e+18,Public Rack - Lawndale Ave & Roosevelt,2,2,In Service,41.866225,-87.717918,"(41.866225, -87.717918)",Pulaski,0.408262,Roosevelt & Lawndale,0.002163,0.001295,0.000000,0.000000
1415,1.715850e+18,Public Rack - Ashland Ave & 74th St,2,2,In Service,41.759735,-87.663736,"(41.759735, -87.663736)",Ashland/63rd,0.819176,74th Street & Ashland,0.013163,0.001657,0.000000,0.000000
1416,3.200000e+02,Loomis St & Lexington St,19,19,In Service,41.872187,-87.661501,"(41.872187, -87.661501)",Racine,0.172757,Harrison & Loomis,0.083768,0.097854,12.757780,37.920830
1417,5.400000e+01,Ogden Ave & Chicago Ave,19,19,In Service,41.896362,-87.654061,"(41.896362458, -87.6540612729)",Chicago,0.038891,Chicago & Milwaukee (Blue Line),0.033492,0.161562,21.361908,26.010023
1418,6.930000e+02,Baltimore Ave & 87th St,15,15,In Service,41.737336,-87.548515,"(41.737335600416664, -87.54851460456847)",87th,2.446187,87th Street & Baltimore,0.012881,0.370860,48.765399,3.148026

In [32]:
stations.to_csv('stations_efficiency.csv')